In [11]:
import numpy as np

In [12]:
a = np.array([1,2,3], order='F')
print(a)

[1 2 3]


In [13]:
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [14]:
c = np.array([1,2,3,4,5], ndmin=2)
c

array([[1, 2, 3, 4, 5]])

In [15]:
d = np.array([1,2,3], dtype=complex)
d

array([1.+0.j, 2.+0.j, 3.+0.j])

In [16]:
dt = np.dtype(np.int32)
dt

dtype('int32')

In [18]:
dt = np.dtype('i2')
dt

dtype('int16')

In [23]:
dt = np.dtype('<i2')
dt

dtype('int16')

In [26]:
dt = np.dtype([('age', np.int8)])
a = np.array([(10,),(20,),(30,)], dtype=dt)
a

array([(10,), (20,), (30,)], dtype=[('age', 'i1')])

In [31]:
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
a = np.array([('a', 21, 90), ('b', 22, 59), ('c', 23, 75)], dtype=student)
print(a)

[(b'a', 21, 90.) (b'b', 22, 59.) (b'c', 23, 75.)]


In [33]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [36]:
x = np.arange(1, 10, 2)
x

array([1, 3, 5, 7, 9])

In [38]:
x = np.linspace(2.0, 3.0, num=5, retstep=True)
x

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [43]:
a = np.array([1,2,4])
b = np.array([1,3,4])
c = np.append(a, b)
d = np.sort(c)
print(d)

[1 1 2 3 4 4]
