In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

# Concatenate

In [3]:
arr1 = np.arange(9).reshape(3,3)

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
arr2 = np.arange(9).reshape(3,3)

In [6]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.concatenate([arr1,arr2],axis=1) # 将两个矩阵连接起来

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [13]:
s1 = Series([1,2],index=['A','B'])

In [14]:
s1

A    1
B    2
dtype: int64

In [15]:
s2 = Series([3,4],index=['C','D'])

In [16]:
s2

C    3
D    4
dtype: int64

In [17]:
pd.concat([s1,s2])

A    1
B    2
C    3
D    4
dtype: int64

In [20]:
df1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

In [21]:
df1

X         Y         Z
0  1.422318 -1.445023  0.919068
1 -0.129141  0.163494  2.325149
2  0.098348  1.808656 -0.173859
3  1.290618  1.151348  0.481427

In [26]:
df2 = DataFrame(np.random.randn(3,2),columns=['X','Y'])

In [27]:
df2

X         Y
0 -0.560399 -1.863592
1  1.659095  0.769796
2 -0.033967 -0.616525

In [28]:
pd.concat([df1,df2])

X         Y         Z
0  1.422318 -1.445023  0.919068
1 -0.129141  0.163494  2.325149
2  0.098348  1.808656 -0.173859
3  1.290618  1.151348  0.481427
0 -0.560399 -1.863592       NaN
1  1.659095  0.769796       NaN
2 -0.033967 -0.616525       NaN

# Combine

In [29]:
s1.combine_first(s2)  # 会用s2里的值填充s1 如果s1对应的值为空

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float64