# 快速创建数组

In [1]:
import numpy as np

In [2]:
np.random.randn(10) # 创建10个随机数组

array([ 0.08914778,  0.28912241,  0.14469038, -1.57212899,  0.04475437,
       -0.61458837, -0.5671614 , -0.5548607 ,  0.73097175,  1.33804232])

In [4]:
np.random.randint(10)

4

In [6]:
np.random.randint(10, size=20).reshape(4,5) # 创建20个10以内的数  reshape() 编程几行几列

array([[3, 1, 4, 1, 6],
       [5, 9, 5, 8, 3],
       [8, 6, 7, 9, 2],
       [8, 3, 9, 3, 3]])

# 数组的运算

In [7]:
a = np.random.randint(10, size=20).reshape(4,5) 

In [8]:
a

array([[5, 1, 7, 9, 2],
       [2, 8, 6, 4, 6],
       [0, 2, 5, 5, 4],
       [8, 0, 4, 9, 2]])

In [9]:
b = np.random.randint(10, size=20).reshape(4,5) 

In [10]:
a + b

array([[ 7,  7,  8, 17,  5],
       [ 6, 14, 13, 10, 11],
       [ 6,  3, 13, 14,  4],
       [16,  9, 12,  9,  9]])

In [11]:
b


array([[2, 6, 1, 8, 3],
       [4, 6, 7, 6, 5],
       [6, 1, 8, 9, 0],
       [8, 9, 8, 0, 7]])

In [12]:
a - b

array([[ 3, -5,  6,  1, -1],
       [-2,  2, -1, -2,  1],
       [-6,  1, -3, -4,  4],
       [ 0, -9, -4,  9, -5]])

In [14]:
np.mat([[1,2,3], [4,5,6]]) # 创建矩阵

matrix([[1, 2, 3],
        [4, 5, 6]])

In [15]:
a

array([[5, 1, 7, 9, 2],
       [2, 8, 6, 4, 6],
       [0, 2, 5, 5, 4],
       [8, 0, 4, 9, 2]])

In [20]:
np.mat(a) # 将数组转换成矩阵

matrix([[5, 1, 7, 9, 2],
        [2, 8, 6, 4, 6],
        [0, 2, 5, 5, 4],
        [8, 0, 4, 9, 2]])

In [22]:
np.unique(a) # 返回a中的唯一值

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [23]:
sum(a) # 返回所有列的和

array([15, 11, 22, 27, 14])

In [25]:
a.max() #求最大值

9