In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
standardScaler = StandardScaler()
standardScaler.fit(X_train)

StandardScaler()

In [6]:
standardScaler.mean_

array([5.83416667, 3.07666667, 3.71583333, 1.18333333])

In [8]:
standardScaler.scale_ # 描述数据分布范围

array([0.82527731, 0.45013578, 1.76266823, 0.75424723])

In [9]:
X_train = standardScaler.transform(X_train) # 对数据进行归一化

In [10]:
X_train

array([[-1.13194275,  0.05183621, -1.25709041, -1.43631065],
       [-0.52608579,  0.71830178, -1.14362606, -1.30372813],
       [-1.49545692,  0.05183621, -1.25709041, -1.30372813],
       [ 0.20094256, -1.9475605 ,  0.72853566,  0.41984465],
       [ 0.32211395, -0.61462936,  0.55833914,  0.02209709],
       [ 1.0491423 , -0.17031898,  0.72853566,  0.68500969],
       [-0.4049144 , -1.50325012,  0.04774958, -0.11048543],
       [-0.16257162,  1.60692254, -1.14362606, -1.17114561],
       [ 0.20094256,  0.71830178,  0.44487479,  0.55242717],
       [-0.4049144 , -1.05893974,  0.38814262,  0.02209709],
       [ 0.44328534, -0.39247417,  0.33141045,  0.15467961],
       [-0.88959997,  1.60692254, -1.03016172, -1.03856308],
       [ 0.32211395, -0.61462936,  0.16121393,  0.15467961],
       [-0.04140023, -0.83678455,  0.2179461 , -0.24306796],
       [-0.52608579,  0.71830178, -1.25709041, -1.03856308],
       [ 1.17031369, -0.17031898,  1.01219653,  1.21533978],
       [ 2.13968482, -0.

In [11]:
X_test_standardScaler = standardScaler.transform(X_test)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [13]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [14]:
knn_clf.score(X_test_standardScaler, y_test)

0.9